#!/usr/bin/env python
"""
Pips wraps pip, offering to save any packages
which you have installed.
"""

import subprocess, sys, os, re

def find_requirements():
    """get location of requirements.txt, in this directory or parents"""
    search = os.getcwd()
    new_search = None

    while new_search != search:
        if new_search:
            search = new_search

        if os.path.exists(os.path.join(search, 'requirements.txt')):
            return os.path.join(search, 'requirements.txt')

        new_search = os.path.dirname(search)

    return None

def add_reqs(requirements, installed):
    """Add the installed requirements to the requirements file"""
    with open(requirements, 'r+') as reqs:
        # Add newlines to each of the installed items
        installed = [x + '\n' for x in installed]

        # Get the lines to write out
        lines = reqs.readlines() + installed

        # Overwrite the file with the new lines
        reqs.seek(0)
        reqs.write(''.join(lines))
        reqs.truncate()

    print('\ndone!')

REQUIREMENT_RE = (
    r'[-A-Za-z0-9_]+'
    r'( *(<|<=|!=|==|>=|>) *[-A-Za-z0-9_\.]+\,?)*'
    r'(\[( *[-A-Za-z0-9_]+\,?)\])?'
)

def install(args):
    """Offer to add installed packages to requirements.txt"""
    regex = re.compile(REQUIREMENT_RE)

    requirements = find_requirements()
    if requirements:
        installed = []
        for arg in args:
            if regex.match(arg):
                installed.append(arg)

        print('\nAdd the following to requirements.txt?\n')
        print('\n'.join(installed))
        approve = raw_input('\n(y/n): ')

        if approve.lower() == 'y':
            add_reqs(requirements, installed)

def main():
    """Call pip, and check if we should do anything"""
    status = subprocess.call(['pip'] + sys.argv[1:])

    if status == 0:
        if sys.argv[1] == 'install':
            install(sys.argv[2:])


if __name__ == '__main__':
    main()

